### ISSUE TITLE
Swarms become invisible

### ISSUE THREAD

**Issue by corbinyo** [keijiro/Swarm#2]
Hi there,

I am encountering issues with the swarms becoming invisible to my camera at certain points when my scene is running. I am animating the swarms and moving them around. Have you dealt with this issue before?

**Comment by keijiro** [comment]
I guess that it disappears because of inaccurate frustum culling. I wonder if it could be resolved by expanding the bounding box.

https://github.com/keijiro/Swarm/blob/master/Assets/Swarm/CrawlingSwarm.cs#L271

**Comment by corbinyo** [comment]
Thank you, I will try this. The Swarm I am using is the Floating Swarm. I will report back how this goes.

**Comment by corbinyo** [comment]
This works, no issues with disappearing anymore -  thank you. 

Setting are as follows in the "FloatingSwarm.cs" script.:

` Graphics.DrawMeshInstancedIndirect(
                _template.mesh, 0, _material,
                new Bounds(Vector3.zero, Vector3.one * 10000),
                _drawArgsBuffer, 0, _props
            );`
