### ISSUE TITLE
What's _UniqueID?

### ISSUE THREAD

**Issue by Luxiere** [keijiro/Swarm#4]
In the project you created a Material Property Block and `SetFloat("_UniqueID", Random.Value) `to it. Is the _UniqueID the instance unique ID? Why do you need to set this value?

**Comment by keijiro** [comment]
`// This property block is used only for avoiding an instancing bug.`

As noted in the comment, it's a workaround for an instancing bug inside Unity. I can't remember what it was... I think it has been fixed in the current version.
